language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - SDCARD_NAME=sdcard-${EMULATOR_API_LEVEL}.img
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}

    - android-${ANDROID_API_LEVEL}
    - android-${EMULATOR_API_LEVEL}

    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository

    # System images
    - sys-img-${ANDROID_ABI}-android-${EMULATOR_API_LEVEL}

before_script:
  # Create local.properties
  - printf 'bintray.user=${BINTRAY_USER}\nbintray.apikey=${BINTRAY_API_KEY}' > local.properties
  # Create SD card (needed for Cucumber)
  - mksdcard -l ${SDCARD_NAME} "200M" ${SDCARD_NAME}
  # Create emulator
  - echo no | android create avd -f -n emulator-v${EMULATOR_API_LEVEL} -t android-${EMULATOR_API_LEVEL} --abi ${ANDROID_ABI} --sdcard ${SDCARD_NAME}
  - emulator -avd emulator-v${EMULATOR_API_LEVEL} -no-audio -no-window &
  - android-wait-for-emulator
script:
  - android list target
  - ./gradlew jacocoTestReport --info -Pinstall_options=-r,-t